"""add Document,Task,Chunk Tables

Revision ID: 0dafcca0b4c6
Revises: 1ba032ea912a
Create Date: 2025-10-22 07:36:03.734225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '0dafcca0b4c6'
down_revision: Union[str, Sequence[str], None] = '1ba032ea912a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'DONE', 'FAILED', name='documentstatusenum', native_enum=False, length=50), nullable=False),
    sa.Column('total_chunks', sa.BigInteger(), nullable=False),
    sa.Column('complete_chunks', sa.BigInteger(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_uid'), 'document', ['uid'], unique=True)
    op.create_table('chunk',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('uid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('milvus_embedded', sa.Boolean(), nullable=False),
    sa.Column('elastic_embedded', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('chunk_id_document_id_index', 'chunk', ['id', 'document_id'], unique=False)
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_uid'), 'chunk', ['uid'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('document_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('callback_url', sa.NCHAR(length=255), nullable=False),
    sa.Column('payload', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PENDING', 'STARTED', 'SEND_CALLBACK', 'DONE', 'FAILED', name='taskstatusenum', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_document_id'), 'task', ['document_id'], unique=False)
    op.create_index(op.f('ix_task_uid'), 'task', ['uid'], unique=True)
    op.create_index('task_id_uid_document_id_index', 'task', ['id', 'uid', 'document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('task_id_uid_document_id_index', table_name='task')
    op.drop_index(op.f('ix_task_uid'), table_name='task')
    op.drop_index(op.f('ix_task_document_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_chunk_uid'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_index('chunk_id_document_id_index', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_document_uid'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
