"""initial tables

Revision ID: 2ce70f64a2ed
Revises: 
Create Date: 2025-09-02 13:08:20.756120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '2ce70f64a2ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_requests',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('TaskId', sa.BigInteger(), nullable=False),
    sa.Column('UserId', sa.BigInteger(), nullable=False),
    sa.Column('DocumentId', sa.BigInteger(), nullable=False),
    sa.Column('EndpointName', sa.String(), nullable=False),
    sa.Column('ProcessPayload', sa.String(), nullable=False),
    sa.Column('StartTime', mssql.DATETIMEOFFSET(), nullable=False),
    sa.Column('EndTime', mssql.DATETIMEOFFSET(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_process_requests_TaskId'), 'process_requests', ['TaskId'], unique=True)
    op.create_table('process_type',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('process_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TaskId', sa.BigInteger(), nullable=False),
    sa.Column('LogTypeId', sa.Integer(), nullable=False),
    sa.Column('StartTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['LogTypeId'], ['process_type.Id'], ),
    sa.ForeignKeyConstraint(['TaskId'], ['process_requests.TaskId'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_process_logs_TaskId'), 'process_logs', ['TaskId'], unique=False)
    op.create_table('process_result',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('TaskId', sa.BigInteger(), nullable=False),
    sa.Column('DocumentId', sa.Integer(), nullable=False),
    sa.Column('Content', sa.String(), nullable=False),
    sa.Column('CreatedAt', mssql.DATETIMEOFFSET(), nullable=False),
    sa.Column('MappingData', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['TaskId'], ['process_requests.TaskId'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_process_result_TaskId'), 'process_result', ['TaskId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_result_TaskId'), table_name='process_result')
    op.drop_table('process_result')
    op.drop_index(op.f('ix_process_logs_TaskId'), table_name='process_logs')
    op.drop_table('process_logs')
    op.drop_table('process_type')
    op.drop_index(op.f('ix_process_requests_TaskId'), table_name='process_requests')
    op.drop_table('process_requests')
    # ### end Alembic commands ###
